### PR TITLE
Port odoo to Python 3.1x/Werkzeug 2.x, backward …

### PR DESCRIPTION
**Pull request by rajeeshknambiar**
…compatible with Python 3.9/Werkzeug 0.16

task/5104

Signed-off-by: Rajeesh KV <rajeesh.kv@unipart.com>

Description of the issue/feature this PR addresses: Make odoo work with both Python 3.11/Werkzeug 2.2 and Python 3.9/Werkzeug 0.16

Current behavior before PR: error when running against Python 3.11/Werkzeug 2.2

Desired behavior after PR is merged: works with both Python 3.11/Werkzeug 2.2 and Python 3.9/Werkzeug 0.16

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kdwyer** [comment]
Looks good, but have we checked if there are any upstream commits that we can cherry-pick cleanly that implement these changes?

**Comment by rajeeshknambiar** [comment]
> Looks good, but have we checked if there are any upstream commits that we can cherry-pick cleanly that implement these changes?

Only partially (just the opcodes): https://github.com/odoo/odoo/pull/101136
May be cherry-pick it & make other changes on top of it?

**Comment by kdwyer** [comment]
> > Looks good, but have we checked if there are any upstream commits that we can cherry-pick cleanly that implement these changes?
> 
> Only partially (just the opcodes): [odoo#101136](https://github.com/odoo/odoo/pull/101136) May be cherry-pick it & make other changes on top of it?

Yes, generally I'd say if we have an upstream change that we can cherry-pick cleanly, use it.

**Comment by rajeeshknambiar** [comment]
> Yes, generally I'd say if we have an upstream change that we can cherry-pick cleanly, use it.

Cherry picked relevant upstream commits and made changes on top of it.

Tested with Python 3.7, 3.9, 3.10 & 3.11.

**Review by kdwyer — APPROVED** [review]
Not sure we need the "sleep" change, but there is no harm in having it.

**Comment by rajeeshknambiar** [comment]
> Not sure we need the "sleep" change, but there is no harm in having it.

It was part of an upstream commit, didn't want to fight with `git am` there.

**Comment by PeterAlabaster** [comment]
I would like to test this out later as i'm running python 3.8.17, happy with the changes but just want to ensure we don't break existing developer instances when this goes in

**Review by ws-mps — APPROVED** [review]

**Comment by PeterAlabaster** [comment]
NB:
For `python 3.8.17`
Upgrading werkzeug from `Werkzeug-0.16.1` to  `werkzeug-2.3.7` also upgrades markupsafe from `MarkupSafe-1.1.0` to `MarkupSafe-2.1.3`, which seems to break jinja2 when running odoo.

Upgrading jinja2 from `Jinja2-2.11.2` to `jinja2-3.1.2` appears to fix the issue.

Seeing as this MR doesn't force a werkzeug update, happy with it, and we can deal with any dep / python version changes elsewhere.

**Review by PeterAlabaster — APPROVED** [review]

**Pull request merged**
